### ISSUE TITLE
File Not Imcompele

### ISSUE THREAD

**Issue by zhanglaplace** [Hucley/VGGFace2-with-Baidu-SkyDrive#1]
Hi , i unzip the file only get 6095 directories . but  the paper about VggFace2 is 9131, can you share me the full datasets? thanks.

**Comment by HansonSun** [comment]
怎么总是解压失败，有完整的吗

**Comment by Hucley** [comment]
我确认了一下，上传的文件是完整的，其中测试集500类，训练集8631类。因为百度网盘上传大小有限制，训练集是分块压缩的后上传的，所以解压时应直接解压主文件vggface2_train.zip(93.8M)这个文件就直接可以获得完整训练集。而不是首先解压vggface_train.z*文件。如果按照上述方法还是不完整，建议直接从官网下。

**Comment by zhanglaplace** [comment]
@Hucley 好的，我在尝试下，我直接从zip解压的。显示文件末端错误，我再试试吧。多谢了

**Comment by zhanglaplace** [comment]
@Hucley 我同学解压成功了，但是我自己pc解压一直显示末端错误。但是可以表明文件是完整的，之前的评论是我的问题，sorry
